DROP TABLE IF EXISTS `ns_account`;

CREATE TABLE `ns_account` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(35) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`group` VARCHAR(15) NOT NULL,
	`is_active` TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (`id`),
	UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
